<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StandardsSeeder extends Seeder
{
    public function run()
    {
        DB::table('standards')->insert([
            [
                'id' => 1,
                'short_name' => 'Cartilla Fitosanitaria',
                'long_name' => 'Cartilla Fitosanitaria',
                'content' => 'Es necesario adquirir una Cartilla Fitosanitaria si lo que se desea es exportar o movilizar la fruta a zonas con bajo control fitosanitario o de baja prevalencia las cuales son: Michoacán, Sinaloa, Sonora, Baja California y Baja California Sur. Este documento es esencial para que sea posible obtener la siguiente documentación: Certificado Fitosanitario Internacional (CFI), Constancia de Origen de Productos Regulados Fitosanitariamente (COPREF), Certificado Fitosanitario de Movilización Nacional (CFMN). Para conocer acerca de los requisitos fitosanitarios que debes cumplir, es necesario acudir a la Junta Local de Sanidad Vegetal correspondiente a tu municipio.',
                'link' => 'https://www.gob.mx/tramites/ficha/certificado-fitosanitario-de-movilizacion-nacional/SENASICA4502',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 3,
                'short_name' => 'NOM-066-FITO-2002',
                'long_name' => 'NORMA Oficial Mexicana NOM-066-FITO-2002, Especificaciones para el manejo fitosanitario y movilización del aguacate.',
                'content' => 'El objetivo de esta norma es proteger la salud humana, el medio ambiente y la sanidad vegetal al establecer los requisitos permisibles de plaguicidas y otros productos químicos en la producción y comercialización del aguacate. Abre el siguiente enlace para conocer los requerimientos necesarios para cumplirla.',
                'link' => 'https://dof.gob.mx/nota_detalle.php?codigo=2037121&fecha=18/05/2005#gsc.tab=0',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 4,
                'short_name' => 'NOM-128-SCFI-1998',
                'long_name' => 'NORMA Oficial Mexicana NOM-128-SCFI-1998 Información Comercial-Etiquetado de productos agrícolas-Aguacate',
                'content' => 'Esta NOM tiene como objetivo proporcionar a los consumidores información clara, precisa y veraz sobre el producto que están adquiriendo, incluyendo su origen, composición, características y condiciones de almacenamiento y consumo. La norma establece los requisitos que deben cumplir en las etiquetas de los productos agrícolas, por ejemplo, la denominación de venta, el contenido neto, el país de origen y la fecha de caducidad o de consumo preferente.',
                'link' => 'https://www.sinec.gob.mx/SINEC/Vista/Normalizacion/DetalleNorma.xhtml?pidn=VFg0ZDZxdW9lelhPeW8rTW53VW9jdz09',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 5,
                'short_name' => 'NOM-075-FITO-1997',
                'long_name' => 'MODIFICACIÓN de la Norma Oficial Mexicana NOM-075-FITO-1997, Por lo que se establecen los requisitos y especificaciones fitosanitarias para la movilización de frutos hospedadores de moscas de la fruta',
                'content' => 'La Norma Oficial Mexicana NOM-075-FITO-1997 establece las especificaciones y requisitos fitosanitarios para la importación de plantas, productos vegetales y otros materiales relacionados con las plantas en México, establece medidas de control para la adecuada certificación de la calidad fitosanitaria de dichos productos.',
                'link' => 'https://www.gob.mx/senasica/documentos/nom-075-fito-1997',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 6,
                'short_name' => 'NOM-077-FITO-2000',
                'long_name' => 'Modificación de la Norma Oficial Mexicana NOM-077-FITO-2000, Por la que se establecen los requisitos y especificaciones para la realización de estudios de efectividad biológico de los insumos de nutrición vegetal',
                'content' => 'Esta norma establece los requisitos y especificaciones que deben cumplir los insumos de nutrición vegetal para ser evaluados y certificados, estas regulaciones tienen el objetivo específico de constatar que los productos que se utilizan en la agricultura mejoren el crecimiento y la producción de las plantas de forma segura.',
                'link' => 'https://www.gob.mx/senasica/documentos/nom-077-fito-2000?state=published',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 7,
                'short_name' => 'NOM-081-FITO-2001',
                'long_name' => 'NORMA Oficial Mexicana NOM-081-FITO-2001, Manejo y eliminación de focos de infestación de plagas, mediante el establecimiento o reordenamiento de fechas de siembra, cosecha y destrucción de residuos',
                'content' => 'Esta norma tiene como principal objetivo prevenir y controlar las epidemias agrícolas que pueden llegar a dañar la producción agrícola. A su vez, el cumplimiento de esta normativa ayuda a garantizar la seguridad alimentaria y la protección de la salud humana.',
                'link' => 'https://www.gob.mx/senasica/documentos/nom-081-fito-2001?state=published',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 8,
                'short_name' => 'NOM-069-FITO-1995',
                'long_name' => 'NORMA Oficial Mexicana NOM-069-FITO-1995, Para el establecimiento y reconocimiento de zonas libres de plagas',
                'content' => 'El objetivo del cumplimiento de esta normativa radica en el establecimiento de los requerimientos y procesos para la creación de zonas libres de plagas en México, con el fin de prevenir la introducción y diseminación de plagas que puedan llegar a dañar la sanidad agropecuaria del país.',
                'link' => 'https://dof.gob.mx/nota_detalle.php?codigo=4899870&fecha=18/11/1998#gsc.tab=0',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 9,
                'short_name' => 'NOM-144-SEMARNAT-2017',
                'long_name' => 'NORMA Oficial Mexicana NOM-144-SEMARNAT-2017, Que establece las medidas fitosanitarias y los requisitos de la marca reconocidas internacionalmente para el embalaje de madera que se utiliza en el comercio internacional de bienes y mercancías.',
                'content' => 'Esta norma tiene como principal objetivo prevenir la introducción y proliferación de plagas y enfermedades que puedan afectar la sanidad de los cultivos mediante el embalaje utilizado de madera.',
                'link' => 'https://www.dof.gob.mx/nota_detalle.php?codigo=5514060&fecha=22/02/2018#gsc.tab=0',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 10,
                'short_name' => 'NOM-076-FITO-1997',
                'long_name' => 'Norma Oficial Mexicana NOM-076-FITO-1997, Por la que se establecen los requisitos y especificaciones fitosanitarias para el sistema preventivo y dispositivo nacional de emergencia contra las moscas exóticas de la fruta.',
                'content' => 'Esta NOM puntualiza las especificaciones fitosanitarias para el sistema preventivo y dispositivo nacional de emergencia contra la proliferación de las moscas exóticas de la fruta en México. Esta norma tiene como objetivo prevenir la introducción y propagación de moscas exóticas de la fruta que puedan afectar la producción agrícola y la exportación de productos agrícolas mexicanos.',
                'link' => 'https://www.gob.mx/senasica/documentos/nom-076-fito-1999?state=published',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 11,
                'short_name' => 'NOM-082-SAG-FITO/SSA1-2017',
                'long_name' => 'NORMA Oficial Mexicana NOM-082-SAG-FITO/SSA1-2017. Límites máximos de residuos. Lineamientos técnicos y procedimiento de autorización y revisión.',
                'content' => 'Esta norma establece los procedimientos y lineamientos técnicos para la autorización y revisión de los registros de plaguicidas y establece la obligatoriedad de su cumplimiento.',
                'link' => 'https://www.dof.gob.mx/nota_detalle.php?codigo=5499806&fecha=04/10/2017#gsc.tab=0',
                'charter_id' => 1,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 12,
                'short_name' => 'Solicitud Certificado de Exportación',
                'long_name' => 'Solicitud certificado de exportación. Instructivo de llenado del formato para realizar el trámite de certificación de exportación.',
                'content' => 'El primer link redirige al documento de solicitud, en donde se adjunta el instructivo de llenado del formato para realizar el trámite de certificación exportación, así como el Manual de Apoyo para el Exportador Certificados de Apoyo a la Exportación de Productos y Servicios. Y también, se adjunta los campos a llenar del formato junto con los requisitos documentales necesarios para la solicitud de trámite.',
                'link' => 'https://www.gob.mx/cms/uploads/attachment/file/652269/COFEPRIS-01-007-B.pdf',
                'charter_id' => 1,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 13,
                'short_name' => 'Certificado Exportación Buenas Prácticas Sanitarias',
                'long_name' => 'Certificado para exportación de conformidad de buenas prácticas sanitarias.',
                'content' => 'El primer link redirige al documento de solicitud, en donde se adjunta el instructivo de llenado del formato para realizar el trámite de certificación de exportación de conformidad de buenas prácticas sanitarias, así como el Manual de Apoyo para el Exportador Certificados de Apoyo a la Exportación de Productos y Servicios. Y también, se adjunta los campos a llenar del formato junto con los requisitos documentales necesarios para la solicitud de trámite.',
                'link' => 'https://www.gob.mx/cms/uploads/attachment/file/652271/COFEPRIS-01-007-D.pdf',
                'charter_id' => 1,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 14,
                'short_name' => 'Certificado Exportación Análisis de Producto',
                'long_name' => 'Certificación para exportación análisis del producto.',
                'content' => 'El primer link redirige al documento de solicitud, en donde se adjunta el instructivo de llenado del formato para realizar el trámite de certificación para exportación análisis del producto, así como el Manual de Apoyo para el Exportador Certificados de Apoyo a la Exportación de Productos y Servicios. Y también, se adjunta los campos a llenar del formato junto con los requisitos documentales necesarios para la solicitud de trámite.',
                'link' => 'https://www.gob.mx/cms/uploads/attachment/file/652271/COFEPRIS-01-007-D.pdf',
                'charter_id' => 1,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 15,
                'short_name' => 'Documentación para Primus GFS',
                'long_name' => 'Certificación de Primus GFS y auditorías GAP y GMP.',
                'content' => 'La certificación de Primus GFS es una auditoría necesaria para ciertas certificaciones, Primus GFS comprende una serie de lineamientos estándar que incluyen diferentes secciones de la línea de producción entre las cuales se encuentra la cadena primaria. Así mismo, ofrece auditorías GAP y GMP.',
                'link' => 'https://primusgfs.com/pgfs-v3-2/',
                'charter_id' => 1,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 16,
                'short_name' => 'IFA V6 (Global Gap)',
                'long_name' => 'Norma de Aseguramiento Integrado de Fincas (IFA) V6.',
                'content' => 'La norma de Aseguramiento Integrado de Fincas (IFA) V6 entrará en vigor el día 1 de enero de 2024, esta norma tendrá un reconocimiento GFSI y será necesario cubrir con los requerimientos que esta norma expida para poder hacer auditorías en tu huerto.',
                'link' => 'https://www.globalgap.org/es/for-producers/globalg.a.p./integrated-farm-assurance-ifa/IFA-V6/',
                'charter_id' => 1,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 17,
                'short_name' => 'IFA V5 (Global Gap)',
                'long_name' => 'Norma de Aseguramiento Integrado de Fincas (IFA) V5.',
                'content' => 'La norma de Aseguramiento Integrado de Fincas (IFA) V5 actualmente se encuentra vigente para llevar a cabo auditorías, sin embargo, esta norma ya no cuenta con un reconocimiento GFSI, se encontrará vigente hasta el día 31 de diciembre de 2023.',
                'link' => 'https://www.globalgap.org/es/for-producers/globalg.a.p./integrated-farm-assurance-ifa/versions-overview/index.html#:~:text=Norma%20IFA%20v5.-',
                'charter_id' => 1,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 18,
                'short_name' => 'Expedición del Certificado Fitosanitario Internacional (CFI)',
                'long_name' => 'Solicitud del Certificado Fitosanitario Internacional (CFI).',
                'content' => 'Para solicitar el certificado fitosanitario internacional debes cumplir con ciertos requisitos los cuales se encuentran establecidos en el siguiente link.',
                'link' => 'https://www.gob.mx/tramites/ficha/certificado-fitosanitario-internacional/SENASICA649',
                'charter_id' => 1,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 19,
                'short_name' => 'CODEX STAN 197-1995',
                'long_name' => 'Norma del CODEX para el Aguacate CODEX STAN 197-1995.',
                'content' => 'La normativa CODEX un estándar internacional que establece los requerimientos necesarios de calidad para el aguacate fresco destinado al consumo humano.',
                'link' => 'https://alimentosargentinos.magyp.gob.ar/contenido/marco/Codex_Alimentarius/normativa/codex/stan/197-1995.PDF',
                'charter_id' => 2,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 20,
                'short_name' => 'NMX-FF-016-SCFI-2016',
                'long_name' => 'NMX-FF-016-SCFI-2016 PRODUCTOS ALIMENTICIOS NO INDUSTRIALIZADOS PARA USO HUMANO-FRUTA FRESCA-AGUACATE HASS (Persea americana Mill)-ESPECIFICACIONES.',
                'content' => 'Esta NMX establece los requerimientos necesarios de calidad y características físicas que deben cumplir los aguacates Hass frescos destinados al consumo humano, esta NMX tiene el objetivo de asegurar su inocuidad y a su vez mejorar la competitividad de los productores.',
                'link' => 'https://www.sinec.gob.mx/SINEC/Vista/Normalizacion/DetalleNMX.xhtml?pidn=TDNSQS9kS0szQi80STdGSTlITjFkZz09',
                'charter_id' => 2,
                'business_id' => 2,
                'fruit_id' => 1,
            ],
            [
                'id' => 21,
                'short_name' => 'Ley Federal de Sanidad Vegetal',
                'long_name' => 'Ley Federal de Sanidad Vegetal.',
                'content' => 'En esta ley se creó con el fin de ayudar a los productores a proteger la agricultura y la industria agroalimentaria de México de enfermedades y plagas que puedan afectar la producción y la calidad de los productos agrícolas, esta ley por otro lado establece también sanciones y multas para aquellos que incumplan con los requerimientos sanitarios necesarios.',
                'link' => 'https://www.gob.mx/profepa/documentos/ley-federal-de-sanidad-vegetal#:~:text=Tiene%20por%20objeto%20regular%20y,orden%20p%C3%BAblico%20e%20inter%C3%A9s%20social.',
                'charter_id' => 2,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
            [
                'id' => 22,
                'short_name' => 'Norma de Inocuidad de los Productos Agrícolas Frescos',
                'long_name' => 'Norma de Inocuidad de los Productos Agrícolas Frescos.',
                'content' => 'La norma se enfoca en la prevención de riesgos para la salud pública y el medio ambiente, promoviendo prácticas de manejo integrado de plagas, uso responsable de fertilizantes y otros productos químicos, y gestión adecuada de residuos.',
                'link' => 'https://www.oirsa.org/contenido/2020-2/2021/Inocuidad%20Webinar/LAC%20Intro%20PSR-OIRSA.pdf',
                'charter_id' => 2,
                'business_id' => 1,
                'fruit_id' => 1,
            ],
        ]);
    }
}
